name: CHANGELOG reminder

on:
  pull_request_target:
    types: [opened]

jobs:
  remind-of-changelog:
    if: github.repository == 'cargo-public-api/cargo-public-api' && !startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # So we can comment on the PR
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4 # So the gh command knows what repo to work with
      - run: |
          gh pr review ${{ github.event.pull_request.number }} --comment --body "If this change deserves mention to users, please don't forget to update [CHANGELOG.md](https://github.com/cargo-public-api/cargo-public-api/blob/main/CHANGELOG.md), [public-api/CHANGELOG.md](https://github.com/cargo-public-api/cargo-public-api/blob/main/public-api/CHANGELOG.md), [rustdoc-json/CHANGELOG.md](https://github.com/cargo-public-api/cargo-public-api/blob/main/rustdoc-json/CHANGELOG.md) and/or [rustup-toolchain/CHANGELOG.md](https://github.com/cargo-public-api/cargo-public-api/blob/main/rustup-toolchain/CHANGELOG.md). Thanks!"
