name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "33 3 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  # The purpose of this job is to detect problems like
  # https://github.com/cargo-public-api/cargo-public-api/issues/61 ourselves
  cargo-install:
    runs-on: ubuntu-latest
    steps:
      - run: cargo install cargo-public-api

  # The purpose of running every night is to detect when a change to
  # https://github.com/rust-lang/rust/tree/master/src/rustdoc-json-types
  # requires that we release a new version of public-api to be compatible with
  # the latest nightly toolchain
  ci:
    uses: ./.github/workflows/CI.yml

  # If Rust nightly changes output, auto-create a PR with the new blessed
  # output, which maintainers can conveniently merge after manual review. Note
  # that we must also bump MINIMUM_NIGHTLY_RUST_VERSION_FOR_TESTS to this
  # version, otherwise tests will fail.
  auto-bless:
    environment:
      name: CICD-fork
      url: https://github.com/EnselicCICD/cargo-public-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup install nightly --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get install -y zsh && zsh --version
      - run: ./scripts/cargo-test.sh --bless
      - id: latest-nightly
        run: echo "version=nightly-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - run: |
          [ -z "$(git status --porcelain)" ] || echo "${{ steps.latest-nightly.outputs.version }}" > cargo-public-api/MINIMUM_NIGHTLY_RUST_VERSION_FOR_TESTS
      - uses: peter-evans/create-pull-request@v4
        with:
          title: Bless `${{ steps.latest-nightly.outputs.version }}` output
          commit-message: Bless `${{ steps.latest-nightly.outputs.version }}` output
          author: EnselicCICD <junta-pixlar0l@icloud.com>
          body: Automatically created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
          token: ${{ secrets.ENSELICCICD_GITHUB_TOKEN }}
          push-to-fork: EnselicCICD/cargo-public-api
          branch: create-pull-request/${{ steps.latest-nightly.outputs.version }}
